/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Container;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author shivamawasthi
 */
public class LinguisticValue1 extends javax.swing.JFrame {

    /**
     * Creates new form LinguisticValue1
     */
    
    double[] range =null;
    Container infra = null;
    
    double[] mfValue = null;
    List formVal[] = null;
    List formVal1[] = null;
    Preview p = null;
    Container plot = null;
    JPanel j = null;
    
    
    
    public LinguisticValue1(String heading) {
        initComponents();
        jTextField1.setText(null);
        jLabel1.setText(heading);
        jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jTextField7.setEnabled(false);
            jLabel4.setText(null);
            jLabel5.setText(null);
            jLabel6.setText(null);
            jLabel7.setText(null);
            jLabel8.setText(null);
            j = new JPanel();
            j.setPreferredSize(new Dimension(409, 312));
            
            
            mfValue = new double[6];
            formVal1 = new ArrayList[3];
            formVal1[0] = new ArrayList();
            formVal1[1] = new ArrayList();
            formVal1[2] = new ArrayList();
            formVal = new ArrayList[3];
            formVal[0] = new ArrayList();
            formVal[1] = new ArrayList();
            formVal[2] = new ArrayList();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setText("Name");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel3.setText("Membership Function");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select MF", "Triangular", "Gaussian", "Gauangle" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Preview");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTextField2)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(33, 33, 33)
                                        .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(53, 53, 53)
                                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(20, 20, 20))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(34, 34, 34)
                                .add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(21, 21, 21))))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton2))
                            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 348, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 7, Short.MAX_VALUE))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(58, 58, 58)
                                .add(jLabel2)
                                .add(67, 67, 67))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                        .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 179, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(161, 161, 161)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel1))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1)
                .add(9, 9, 9)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(jLabel15))
                .add(25, 25, 25)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(jLabel10)
                    .add(jLabel11))
                .add(12, 12, 12)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(jLabel13)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1)))
        );

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(405, 312));
        jInternalFrame1.setVisible(true);

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 403, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 310, Short.MAX_VALUE)
        );

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 780, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton4)
                    .add(jLabel17)
                    .add(jButton3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!"".equals(jTextField1.getText()))
        {
            if(!"Select MF".equals(jComboBox1.getSelectedItem()))
            {
                if(!"".equals(jTextField2.getText()))
                {
                    try
                    {
                    mfValue[0] = Double.parseDouble(jTextField2.getText());
                    }catch(NumberFormatException e)
                    {
                        jLabel9.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                    
                    if(!"".equals(jTextField3.getText()))
                    {
                        try
                    {
                    mfValue[1] = Double.parseDouble(jTextField3.getText());
                    }catch(NumberFormatException e)
                    {
                        jLabel10.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                        
                       if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                       {
                           if(!"".equals(jTextField4.getText()))
                        {
                            try
                                   {
                                       mfValue[2] = Double.parseDouble(jTextField4.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel11.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       }
                            
                            
                            if(!"".equals(jTextField6.getText()))
                           {
                               try
                                   {
                                       mfValue[3] = Double.parseDouble(jTextField6.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel12.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       }
                               
                               if(!"".equals(jTextField5.getText()))
                               {
                                   try
                                       {
                                          mfValue[4] = Double.parseDouble(jTextField5.getText());
                                        }catch(NumberFormatException e)
                                           {
                                               jLabel13.setText("*");
                                               jLabel17.setText("*  Please enter correct value");
                                            }
                                   
                                  if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                                  {
                                      if(!"".equals(jTextField7.getText()) )  
                                   {
                                            try
                                               {
                                                 mfValue[5] = Double.parseDouble(jTextField7.getText());
                                                  }catch(NumberFormatException e)
                                                       {
                                                           jLabel14.setText("*");
                                                           jLabel17.setText("*  Please enter correct value");
                                                        }
                                       
                                   }else
                                   {
                                       jLabel14.setText("*");
                                       jLabel17.setText("*  Please enter correct value");
                                   }
                                  }
                                   
                               }else
                               {
                                   jLabel13.setText("*");
                                   jLabel17.setText("*  Please enter correct value");
                               }
                               
                           }else
                           {
                               jLabel12.setText("*");
                               jLabel17.setText("*  Please enter correct value");
                           }
                            
                            
                            
                        }else
                        {
                            jLabel11.setText("*");
                            jLabel17.setText("*  Please enter correct value");
                        }
                       }else // Start for lower MF
                       {
                           if(!"".equals(jTextField6.getText()))
                           {
                                try
                                   {
                                       mfValue[3] = Double.parseDouble(jTextField6.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel12.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       } 
                               
                               
                               
                               if(!"".equals(jTextField5.getText()))
                               {
                                   try
                                       {
                                          mfValue[4] = Double.parseDouble(jTextField5.getText());
                                        }catch(NumberFormatException e)
                                           {
                                               jLabel13.setText("*");
                                               jLabel17.setText("*  Please enter correct value");
                                            }
                                   
                                  if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                                  {
                                      if(!"".equals(jTextField7.getText()) )  
                                   {
                                       
                                   }else
                                   {
                                       jLabel14.setText("*");
                                       jLabel17.setText("*  Please enter correct value");
                                   }
                                  }
                                   
                               }else
                               {
                                   jLabel13.setText("*");
                                   jLabel17.setText("*  Please enter correct value");
                               }
                               
                           }else
                           {
                               jLabel12.setText("*");
                               jLabel17.setText("*  Please enter correct value");
                           }
                       }
                        
                    }else
                    {
                        jLabel10.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                    
                }else
                {
                    jLabel9.setText("*");
                    jLabel17.setText("*  Please enter correct value");
                }
                
            }else{
                jLabel15.setText("*");
                jLabel17.setText("*  Please enter correct value");
            }
            
        }else
        {
            jLabel16.setText("*");
            jLabel17.setText("*  Please enter correct value");
        }
        
        
        if(jLabel17.getText() == null)
        {
            p = new Preview();
            plot = p.graph(jLabel1.getText(),range[0],range[1],(String)jComboBox1.getSelectedItem(),jTextField1.getText(),mfValue, true);
            formVal[0].add(jTextField1.getText());
            formVal[1].add(jComboBox1.getSelectedItem());
            formVal[2].add(mfValue);
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);
            
            mfValue = new double[6];
            jComboBox1.setSelectedIndex(0);
           jInternalFrame1.setContentPane(j);
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        
        if(!"".equals(jTextField1.getText()))
        {
            jLabel16.setText(null);
            jLabel17.setText(null);
        }
        
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        
        if(!"".equals(jTextField2.getText()))
        {
            jLabel9.setText(null);
            jLabel17.setText(null);
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        
        if(!"".equals(jTextField3.getText()))
        {
            jLabel10.setText(null);
            jLabel17.setText(null);
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        
        if(!"".equals(jTextField4.getText()))
        {
            jLabel11.setText(null);
            jLabel17.setText(null);
        }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
        if(!"".equals(jTextField6.getText()))
        {
            jLabel12.setText(null);
            jLabel17.setText(null);
        }
        
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(!"".equals(jTextField5.getText()))
        {
            jLabel13.setText(null);
            jLabel17.setText(null);
        }
        
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
        if(!"".equals(jTextField7.getText()))
        {
            jLabel14.setText(null);
            jLabel17.setText(null);
        }
        
    }//GEN-LAST:event_jTextField7FocusLost

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
        if(!"Select MF".equals(jComboBox1.getSelectedItem()))
        {
            jLabel15.setText(null);
            jLabel17.setText(null);
        }
        
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedItem().equals("Select MF"))
        {
            jTextField2.setEnabled(false);
            jTextField2.setText(null);
            jTextField3.setEnabled(false);
            jTextField3.setText(null);
            jTextField4.setEnabled(false);
            jTextField4.setText(null);
            jTextField5.setEnabled(false);
            jTextField5.setText(null);
            jTextField6.setEnabled(false);
            jTextField6.setText(null);
            jTextField7.setEnabled(false);
            jTextField7.setText(null);
            jLabel4.setText(null);
            jLabel5.setText(null);
            jLabel6.setText(null);
            jLabel7.setText(null);
            jLabel8.setText(null);
            jInternalFrame1.setContentPane(j);
            
        }else
            if(jComboBox1.getSelectedItem().equals("Gaussian"))
            {
                jTextField4.setEnabled(false);
                jTextField4.setText(null);
                jTextField7.setEnabled(false);
                jTextField7.setText(null);
                jLabel6.setText(null);
                jLabel4.setText("Mean");
                jLabel5.setText("Spread");
                jLabel7.setText("Upper MF");
                jLabel8.setText("Lower MF");
                jTextField2.setEnabled(true);
                jTextField2.setText(null);
                jTextField3.setEnabled(true);
                jTextField3.setText(null);
                jTextField5.setEnabled(true);
                jTextField5.setText(null);
                jTextField6.setEnabled(true);    
                jTextField6.setText(null);
                mfValue[2] = 0;
                mfValue[5] = 0;

            }else
            {
                if(jComboBox1.getSelectedItem().equals("Triangular"))
                {
                jTextField4.setEnabled(true);
                jTextField4.setText(null);
                jTextField7.setEnabled(true);
                jTextField7.setText(null);
                jTextField2.setEnabled(true);
                jTextField2.setText(null);
                jTextField3.setEnabled(true);
                jTextField3.setText(null);
                jTextField5.setEnabled(true);
                jTextField5.setText(null);
                jTextField6.setEnabled(true); 
                jTextField6.setText(null);
                jLabel7.setText("Upper MF");
                jLabel8.setText("Lower MF");
                jLabel4.setText("Start");
                jLabel5.setText("Peak");
                jLabel6.setText("End");
                }else
                    if(jComboBox1.getSelectedItem().equals("Gauangle"))
                    {
                        jTextField4.setEnabled(true);
                        jTextField4.setText(null);
                        jTextField7.setEnabled(true);
                        jTextField7.setText(null);
                        jTextField2.setEnabled(true);
                        jTextField2.setText(null);
                        jTextField3.setEnabled(true);
                        jTextField3.setText(null);
                        jTextField5.setEnabled(true);
                        jTextField5.setText(null);
                        jTextField6.setEnabled(true);
                        jTextField6.setText(null);
                        jLabel7.setText("Upper MF");
                        jLabel8.setText("Lower MF");
                        jLabel4.setText("Start");
                        jLabel5.setText("Center");
                        jLabel6.setText("End");
                    }
                
            }
        
                
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Size "+formVal[0].size());
        
        Iterator i = formVal[0].iterator();
        Iterator i1 = formVal[1].iterator();
        Iterator i2 = formVal[2].iterator();
        while(i.hasNext())
        {
            //String t = (String) i.next();
            //String t1 = (String) i1.next();
            //Object t2 = i2.next();
            formVal1[0].add(i.next());
            formVal1[1].add(i1.next());
            formVal1[2].add(i2.next());
        }
        System.out.println("Size1 "+formVal1[0].size());
        
        dispose();
                
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         if(!"".equals(jTextField1.getText()))
        {
            if(!"Select MF".equals(jComboBox1.getSelectedItem()))
            {
                if(!"".equals(jTextField2.getText()))
                {
                    try
                    {
                    mfValue[0] = Double.parseDouble(jTextField2.getText());
                    }catch(NumberFormatException e)
                    {
                        jLabel9.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                    
                    if(!"".equals(jTextField3.getText()))
                    {
                        try
                    {
                    mfValue[1] = Double.parseDouble(jTextField3.getText());
                    }catch(NumberFormatException e)
                    {
                        jLabel10.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                        
                       if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                       {
                           if(!"".equals(jTextField4.getText()))
                        {
                            try
                                   {
                                       mfValue[2] = Double.parseDouble(jTextField4.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel11.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       }
                            
                            
                            if(!"".equals(jTextField6.getText()))
                           {
                               try
                                   {
                                       mfValue[3] = Double.parseDouble(jTextField6.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel12.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       }
                               
                               if(!"".equals(jTextField5.getText()))
                               {
                                   try
                                       {
                                          mfValue[4] = Double.parseDouble(jTextField5.getText());
                                        }catch(NumberFormatException e)
                                           {
                                               jLabel13.setText("*");
                                               jLabel17.setText("*  Please enter correct value");
                                            }
                                   
                                  if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                                  {
                                      if(!"".equals(jTextField7.getText()) )  
                                   {
                                            try
                                               {
                                                 mfValue[5] = Double.parseDouble(jTextField7.getText());
                                                  }catch(NumberFormatException e)
                                                       {
                                                           jLabel14.setText("*");
                                                           jLabel17.setText("*  Please enter correct value");
                                                        }
                                       
                                   }else
                                   {
                                       jLabel14.setText("*");
                                       jLabel17.setText("*  Please enter correct value");
                                   }
                                  }
                                   
                               }else
                               {
                                   jLabel13.setText("*");
                                   jLabel17.setText("*  Please enter correct value");
                               }
                               
                           }else
                           {
                               jLabel12.setText("*");
                               jLabel17.setText("*  Please enter correct value");
                           }
                            
                            
                            
                        }else
                        {
                            jLabel11.setText("*");
                            jLabel17.setText("*  Please enter correct value");
                        }
                       }else // Start for lower MF
                       {
                           if(!"".equals(jTextField6.getText()))
                           {
                                try
                                   {
                                       mfValue[3] = Double.parseDouble(jTextField6.getText());
                                    }catch(NumberFormatException e)
                                      {
                                          jLabel12.setText("*");
                                          jLabel17.setText("*  Please enter correct value");
                                       } 
                               
                               
                               
                               if(!"".equals(jTextField5.getText()))
                               {
                                   try
                                       {
                                          mfValue[4] = Double.parseDouble(jTextField5.getText());
                                        }catch(NumberFormatException e)
                                           {
                                               jLabel13.setText("*");
                                               jLabel17.setText("*  Please enter correct value");
                                            }
                                   
                                  if(!"Gaussian".equals(jComboBox1.getSelectedItem()))
                                  {
                                      if(!"".equals(jTextField7.getText()) )  
                                   {
                                       
                                   }else
                                   {
                                       jLabel14.setText("*");
                                       jLabel17.setText("*  Please enter correct value");
                                   }
                                  }
                                   
                               }else
                               {
                                   jLabel13.setText("*");
                                   jLabel17.setText("*  Please enter correct value");
                               }
                               
                           }else
                           {
                               jLabel12.setText("*");
                               jLabel17.setText("*  Please enter correct value");
                           }
                       }
                        
                    }else
                    {
                        jLabel10.setText("*");
                        jLabel17.setText("*  Please enter correct value");
                    }
                    
                }else
                {
                    jLabel9.setText("*");
                    jLabel17.setText("*  Please enter correct value");
                }
                
            }else{
                jLabel15.setText("*");
                jLabel17.setText("*  Please enter correct value");
            }
            
        }else
        {
            jLabel16.setText("*");
            jLabel17.setText("*  Please enter correct value");
        }
         
         if(jLabel17.getText() == null)
         {
            
              p = new Preview();
              plot = p.graph(jLabel1.getText(),range[0],range[1],(String)jComboBox1.getSelectedItem(),jTextField1.getText(),mfValue, true);
              plot.setPreferredSize(new Dimension(409, 312));
              jInternalFrame1.setContentPane(plot);
              jInternalFrame1.show();
             //jInternalFrame1.setEnabled(false);
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinguisticValue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinguisticValue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinguisticValue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinguisticValue1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinguisticValue1("main").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables


public void range(double[] ran)
{
    range = ran;
}

public List[] mfV()
{
    
   // System.out.println(formVal1[0].size());
    return formVal1;
}

public void init(String heading)
{
    jLabel1.setText(heading);
    jTextField1.setText(null);
        jTextField2.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField2.setText(null);
            jTextField3.setEnabled(false);
            jTextField3.setText(null);
            jTextField4.setEnabled(false);
            jTextField4.setText(null);
            jTextField5.setEnabled(false);
            jTextField5.setText(null);
            jTextField6.setEnabled(false);
            jTextField6.setText(null);
            jTextField7.setEnabled(false);
            jTextField7.setText(null);
            jLabel4.setText(null);
            jLabel5.setText(null);
            jLabel6.setText(null);
            jLabel7.setText(null);
            jLabel8.setText(null);
            jInternalFrame1.setContentPane(j);
           
            
            mfValue = new double[6];
            formVal1 = new ArrayList[3];
            formVal1[0] = new ArrayList();
            formVal1[1] = new ArrayList();
            formVal1[2] = new ArrayList();
            formVal = new ArrayList[3];
            formVal[0] = new ArrayList();
            formVal[1] = new ArrayList();
            formVal[2] = new ArrayList();
            jComboBox1.setSelectedIndex(0);
}


}
