/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import org.jdesktop.layout.GroupLayout;

/**
 *
 * @author shivamawasthi
 */
public class RuleB extends javax.swing.JPanel {

    /**
     * Creates new form RuleB
     */
    
    List l = null, sc = null,sg =null,pg = null;
    GroupLayout.SequentialGroup csg=null ,csg1 = null,csg2 = null,csg3 = null;
    GroupLayout.ParallelGroup cpg = null , cpg1 =null,cpg2 = null,cpg3 = null;
    List list = null, label = null, scrollpane = null;
    
    public RuleB() {
        //initComponents();
        in();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(857, 629));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel1.setText("jLabel1");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(66, 66, 66)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(70, 70, 70)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(87, 87, 87)
                .add(jLabel1)
                .add(228, 228, 228)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel3)
                .add(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .add(jScrollPane2)
                    .add(jScrollPane3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables


public void in()
{
    
    setPreferredSize(new java.awt.Dimension(748, 248));
    
    
        list = new ArrayList();
        label = new ArrayList();
        scrollpane = new ArrayList();
    
    
   for(int i =0;i<1;i++)
        {
            list.add(new javax.swing.JList() );
            label.add(new javax.swing.JLabel());
            scrollpane.add(new javax.swing.JScrollPane());
        } 
    
   
   for( int i =0;i<1;i++)
   
    {
           
            ((JList)list.get(i)).setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
            
        ((JList)list.get(i)).setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ((JScrollPane)scrollpane.get(i)).setViewportView(((JList)list.get(i)));
        
        ((JLabel)label.get(i)).setText("Label "+i);

        }
    
   
   org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
   
   
   csg = layout.createSequentialGroup(); 
   csg1 = call(csg,1,0);
   
   csg2 = layout.createSequentialGroup();
   csg3 = call1(csg2,1,0);
   
    
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(csg1).add(csg3));
        
        
        cpg = layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE);
        cpg1 = call2(cpg,1,0);
        cpg2 = layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false);
        cpg2 = cpg2.add((JScrollPane)scrollpane.get(0), org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE);
       // cpg3 = call3(cpg2,4,1);
   
        
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(cpg1)
                 .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cpg3)
                .addContainerGap(30, Short.MAX_VALUE))
                );
                
  

}





 public GroupLayout.SequentialGroup call(GroupLayout.SequentialGroup c , int n , int i)
    {
        if(n>0)
       
        {  
         call(c.add(52,52,52).add(((JScrollPane)scrollpane.get(i)), org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE), (n-1) , (i+1));
    }
        else{
            
            c = c.addContainerGap(15, Short.MAX_VALUE);
        }
        
        return c;
    
    }  
        
        
        public GroupLayout.SequentialGroup call1(GroupLayout.SequentialGroup c , int n , int i)
    {
         if(n>0)
       
        {  
            if(i>0)
            {
         call(c.add(210, 210, 210)
                .add((JLabel)label.get(i)), (n-1) , (i+1));
    }else
            {
                call(c.add(130, 130, 130)
                .add((JLabel)label.get(i)), (n-1) , (i+1));
            }
        }
        
        
        return c;
    }
    
    
        public GroupLayout.ParallelGroup call2(GroupLayout.ParallelGroup c , int n, int i )
        {
            if(n>0)
            {
                call2(c.add((JLabel)label.get(0)), (n-1) , (i+1));
            }
            
            return c;
        }
        

        public GroupLayout.ParallelGroup call3(GroupLayout.ParallelGroup c , int n, int i )
        {
            if(n>0)
            {
                call3(c.add((JScrollPane)scrollpane.get(i)), (n-1) , (i+1));
            }
            
            return c;
        }

}
